# Generated by Django 2.1 on 2018-10-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
