# Generated by Django 2.2.9 on 2020-01-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0002_alter_product_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='namukilke/products'),
        ),
    ]
