# Generated by Django 2.1 on 2018-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0003_auto_20180921_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
