# Generated by Django 2.1 on 2018-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0005_auto_20180922_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
