# Generated by Django 2.1 on 2018-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namu', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='type',
            field=models.CharField(choices=[('s', 'Stock'), ('r', 'Refund')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('c', 'Cash'), ('m', 'MobilePay'), ('r', 'Refund')], default='c', max_length=1),
        ),
    ]
